import { streamChat, type StreamCallbacks } from "@/lib/llm-client"
import type { ChatMessage } from "@/lib/llm-providers"
import type { LlmConfig } from "@/stores/wiki-store"
import { useWikiStore } from "@/stores/wiki-store"
import { buildContextPack, contextPackToPrompt, type ContextPack } from "./context-engine"
import { resolveNovelModel } from "./model-resolver"
import { hasUsableLlm } from "@/lib/has-usable-llm"
import type { NovelReviewResult } from "./review-adapter"

export type SixReviewDimensionKey = "thrill" | "consistency" | "pacing" | "character" | "continuity" | "pull"
export type DimensionReviewStatus = "error" | "high" | "medium" | "low" | "pass"

/**
 * F-003 (ANL-010 R6): explicit 6-dim → review-`type` mapping.
 *
 * `resolveDecisionGateKey` in deep-chapter-generation.ts buckets a
 * NovelReviewResult into one of 3 gates (consistency / anti_ai / quality) by
 * matching its `type` string against CONSISTENCY_REVIEW_TYPES /
 * ANTI_AI_REVIEW_TYPES sets. A naive string-match would mis-bucket the
 * `character` DIMENSION (key "character") into the `quality` gate, because
 * CONSISTENCY_REVIEW_TYPES contains `character_consistency` — NOT `character`.
 * This mapping translates each of the 6 dimension keys into the review-`type`
 * string that lands it in the CORRECT gate, so the 6-dim fold composes with
 * the existing 18→3 fold instead of silently miscategorizing.
 *
 *   character       → character_consistency  (CONSISTENCY gate — NOT quality)
 *   continuity      → timeline               (CONSISTENCY gate)
 *   consistency     → consistency            (CONSISTENCY gate)
 *   pacing          → plot                   (quality gate)
 *   thrill          → plot                   (quality gate)
 *   pull            → plot                   (quality gate)
 */
export const DIM_TO_GATE_TYPE: Record<SixReviewDimensionKey, string> = {
  thrill: "plot",
  consistency: "consistency",
  pacing: "plot",
  character: "character_consistency",
  continuity: "timeline",
  pull: "plot",
}

/**
 * F-003: error class for malformed dimension-review JSON. Distinguishes a
 * SyntaxError (the model emitted non-JSON) from a runtime error so callers
 * can tell parse failures apart from stream/transport failures
 * (ISS-20260705-020 JSON.parse hardening).
 */
export class DimParseError extends Error {
  readonly raw: string
  readonly parseMessage: string
  constructor(raw: string, parseMessage: string) {
    super(`Dimension review JSON parse failed: ${parseMessage}`)
    this.name = "DimParseError"
    this.raw = raw
    this.parseMessage = parseMessage
  }
}

export interface SixReviewDimensionDefinition {
  key: SixReviewDimensionKey
  label: string
  objective: string
  stages: string[]
  checks: string[]
}

export interface DimensionReviewIssue extends NovelReviewResult {
  dimensionKey: SixReviewDimensionKey
  impact?: string
  rewriteTarget?: string
}

export interface DimensionReviewResult {
  dimensionKey: SixReviewDimensionKey
  score: number
  status: DimensionReviewStatus
  summary: string
  thinking: string
  issues: DimensionReviewIssue[]
}

export interface DimensionReviewCallbacks {
  onThinking?: (dimensionKey: SixReviewDimensionKey, thinking: string) => void
}

export interface SixDimensionReviewCallbacks {
  onDimensionProgress?: (dimensionKey: SixReviewDimensionKey, progress: string) => void
  onDimensionThinking?: (dimensionKey: SixReviewDimensionKey, thinking: string) => void
  onDimensionResult?: (dimensionKey: SixReviewDimensionKey, result: DimensionReviewResult) => void
}

export const SIX_REVIEW_DIMENSION_ORDER: SixReviewDimensionKey[] = [
  "thrill",
  "consistency",
  "pacing",
  "character",
  "continuity",
  "pull",
]

/**
 * F-003 (ANL-010 C1): flatten the 6-dimension review result map into the
 * NovelReviewResult[] shape that deep-chapter-generation.ts's 18→3 fold
 * consumes. Each dimension's issues are tagged with the dimension key via
 * DIM_TO_GATE_TYPE so `resolveDecisionGateKey` buckets them into the correct
 * gate (character → consistency gate, NOT quality). The 6 dims were
 * previously generated by runSixDimensionReview but orphaned — they never
 * reached reviewResults (deep-chapter-generation.ts had no import; verified
 * grep-zero-match pre-F-003). This converter is the wiring point.
 *
 * Severity mapping: a DimensionReviewResult with status "error" yields
 * severity "error" (blocking); status "high"/"medium" yield "warning"
 * (route to stage-5 repair via collectRepairIssues); status "low"/"pass"
 * yield "info". The dimension's own issue severities (when present) are
 * preserved per-issue.
 */
/**
 * CORR-010 (from quality-review): map the dimension-level status to the
 * 3-tier NovelReviewResult severity, then take the MAX of that and the issue's
 * own severity. Previously this copied issue.severity verbatim, so a dimension
 * whose own status was "error" (blocking) could emit only "warning"-severity
 * issues — collectBlockingIssues (which keeps severity === "error" only) would
 * then DROP the dimension entirely, defeating the gate. The dimension's own
 * status is authoritative: status "error" → at least "error"; "high"/"medium"
 * → at least "warning"; "low"/"pass" → "info".
 */
function severityForIssue(
  dimStatus: DimensionReviewStatus,
  issueSeverity: NovelReviewResult["severity"],
): NovelReviewResult["severity"] {
  const fromStatus: NovelReviewResult["severity"] =
    dimStatus === "error" ? "error"
    : dimStatus === "high" || dimStatus === "medium" ? "warning"
    : "info"
  // MAX by blocking order: error > warning > info. The dimension status is the
  // floor; an individual issue may still be more severe than its dimension
  // (e.g. a "medium" dimension surfacing one genuinely blocking issue).
  const order: Record<NovelReviewResult["severity"], number> = { error: 2, warning: 1, info: 0 }
  return order[issueSeverity] > order[fromStatus] ? issueSeverity : fromStatus
}

export function dimensionResultsToReviewResults(
  dimensionResults: Partial<Record<SixReviewDimensionKey, DimensionReviewResult>>,
): NovelReviewResult[] {
  const out: NovelReviewResult[] = []
  for (const key of SIX_REVIEW_DIMENSION_ORDER) {
    const result = dimensionResults[key]
    if (!result) continue
    const reviewType = DIM_TO_GATE_TYPE[key]
    if (result.issues.length > 0) {
      for (const issue of result.issues) {
        out.push({
          severity: severityForIssue(result.status, issue.severity),
          // Override the issue's `type` with the gate-bucketed type so the
          // fold routes correctly. Keep the dimension key in the message
          // prefix for traceability.
          type: reviewType,
          message: `[${result.summary || key}] ${issue.message || ""}`.trim(),
          evidence: issue.evidence || "",
          relatedMemory: issue.relatedMemory || "",
          suggestion: issue.suggestion || "",
        })
      }
    } else {
      // Dimension produced no issues — emit an info-level summary so the
      // gate still records that the dimension was reviewed.
      out.push({
        severity: "info",
        type: reviewType,
        message: `${SIX_REVIEW_DIMENSIONS[key].label}：${result.summary || "pass"}`,
        evidence: "",
        relatedMemory: "",
        suggestion: "",
      })
    }
  }
  return out
}

export const SIX_REVIEW_DIMENSIONS: Record<SixReviewDimensionKey, SixReviewDimensionDefinition> = {
  thrill: {
    key: "thrill",
    label: "爽感密度",
    objective: "判断章节是否建立并兑现有效爽点，而不是只检查剧情是否发生。",
    stages: ["爽点预期识别", "压抑与释放链检查", "主角能动性检查", "爽点密度检查", "爽点失效诊断"],
    checks: ["打脸、反杀、成长、揭谜、奖励兑现是否成立", "期待、阻力、升级、反转、兑现链条是否完整", "爽点是否由主角选择、能力或决断推动", "解释、重复和旁人代打是否削弱爽感"],
  },
  consistency: {
    key: "consistency",
    label: "设定自治",
    objective: "判断设定是否能自洽地推动剧情，而不是临时为剧情让路。",
    stages: ["已登记设定读取", "新设定识别", "规则一致性检查", "代价与边界检查", "设定推动剧情检查"],
    checks: ["能力、物品、组织、地点和规则是否违背旧设定", "新增规则是否有边界、代价和触发条件", "设定是否参与冲突和选择", "是否存在作者硬送或临时开挂"],
  },
  pacing: {
    key: "pacing",
    label: "节奏张力",
    objective: "判断章节是否有推进力、压力变化和持续阅读的节奏。",
    stages: ["场景结构拆分", "张力曲线检查", "信息密度检查", "转折频率检查", "拖沓与跳跃诊断"],
    checks: ["每个场景是否有目标、阻力和结果", "张力是否升级或反转", "说明、内心和背景是否压过行动", "是否存在水文、重复、跳转过快或关键冲突没写足"],
  },
  character: {
    key: "character",
    label: "人设一致",
    objective: "判断人物行为、语言、认知和情绪是否符合既有人设。",
    stages: ["人物状态读取", "行为动机检查", "语言风格检查", "认知边界检查", "成长弧线检查"],
    checks: ["关键选择是否有动机", "台词是否符合身份、性格和关系", "角色是否知道了不该知道的信息", "变化是否有触发原因和过渡"],
  },
  continuity: {
    key: "continuity",
    label: "叙事衔接",
    objective: "判断本章是否和前文、大纲、记忆库顺畅连接。",
    stages: ["前章结尾对接", "章纲目标对接", "时间线检查", "地点与物品连续性检查", "因果链检查"],
    checks: ["开头是否承接上一章地点、状态、情绪和动作", "正文是否完成当前章纲目标", "时间、地点、伤势、物品和伏笔是否连续", "事件是否有清晰因果"],
  },
  pull: {
    key: "pull",
    label: "追读引力",
    objective: "判断读者看完本章后是否有继续阅读下一章的动力。",
    stages: ["本章核心悬念识别", "结尾钩子检查", "下一章承诺检查", "情绪停点检查", "假悬念过滤"],
    checks: ["是否留下新危机、新目标、新反转或新信息", "下一章期待是否明确", "结尾是否停在高张力或强情绪点", "悬念是否有正文证据而不是空钩子"],
  },
}

export function buildDimensionReviewPrompt(
  pack: ContextPack,
  chapterContent: string,
  dimension: SixReviewDimensionDefinition,
): string {
  return `${contextPackToPrompt(pack)}

六维独立审查维度：${dimension.label}
审查目标：${dimension.objective}

专业工作流：
${dimension.stages.map((stage, index) => `${index + 1}. ${stage}`).join("\n")}

检查标准：
${dimension.checks.map((check) => `- ${check}`).join("\n")}

阶段分析要求：
只输出阶段分析，不要输出结构化对象。必须先列已核对依据，再列阶段结论，并明确问题对应的正文证据。

结构化结果格式：
{
  "score": 0,
  "status": "error|high|medium|low|pass",
  "summary": "本维度审查摘要",
  "issues": [
    {
      "severity": "error|warning|info",
      "type": "${dimension.key}",
      "message": "问题描述",
      "evidence": "正文片段",
      "relatedMemory": "相关大纲、记忆或设定",
      "suggestion": "修改建议",
      "impact": "对本维度的影响",
      "rewriteTarget": "建议 AI 修改时定位的原文片段"
    }
  ]
}

章节正文：
${chapterContent.slice(0, 8000)}`
}

export async function reviewChapterDimension({
  llmConfig,
  contextPack,
  chapterContent,
  dimension,
  callbacks = {},
}: {
  llmConfig: LlmConfig
  contextPack: ContextPack
  chapterContent: string
  dimension: SixReviewDimensionDefinition
  callbacks?: DimensionReviewCallbacks
}): Promise<DimensionReviewResult> {
  callbacks.onThinking?.(dimension.key, formatDimensionThinking(dimension, "正在读取上下文..."))
  const analysisPrompt = buildDimensionReviewPrompt(contextPack, chapterContent, dimension)
  const analysis = await runDimensionStage(
    llmConfig,
    dimension,
    analysisPrompt,
    callbacks,
  )

  const finalPrompt = [
    analysisPrompt,
    "",
    "阶段分析结果：",
    analysis,
    "",
    "最终 JSON：",
    "只输出最终 JSON 对象，不要输出解释、标题或 markdown。",
  ].join("\n")
  const finalText = await runDimensionStage(llmConfig, dimension, finalPrompt, callbacks)
  return parseDimensionReviewResult(dimension, finalText, analysis)
}

export async function runSixDimensionReview({
  projectPath,
  chapterContent,
  chapterNumber,
  dimensionKeys,
  callbacks = {},
}: {
  projectPath: string
  chapterContent: string
  chapterNumber?: number
  dimensionKeys?: SixReviewDimensionKey[]
  callbacks?: SixDimensionReviewCallbacks
}): Promise<Partial<Record<SixReviewDimensionKey, DimensionReviewResult>>> {
  const llmConfig = resolveNovelModel(
    useWikiStore.getState().llmConfig,
    useWikiStore.getState().novelConfig,
    "review",
  )
  if (!hasUsableLlm(llmConfig) || !useWikiStore.getState().novelMode) return {}

  const contextPack = await buildContextPack(
    projectPath,
    `六维审查第${chapterNumber || "?"}章`,
    chapterNumber,
  )

  const results: Partial<Record<SixReviewDimensionKey, DimensionReviewResult>> = {}
  for (const key of dimensionKeys ?? SIX_REVIEW_DIMENSION_ORDER) {
    const dimension = SIX_REVIEW_DIMENSIONS[key]
    callbacks.onDimensionProgress?.(key, `${dimension.label}：正在开始专业审查`)
    try {
      const result = await reviewChapterDimension({
        llmConfig,
        contextPack,
        chapterContent,
        dimension,
        callbacks: {
          onThinking: (dimensionKey, thinking) => {
            callbacks.onDimensionThinking?.(dimensionKey, thinking)
          },
        },
      })
      results[key] = result
      callbacks.onDimensionResult?.(key, result)
    } catch (error) {
      // F-003 (ISS-20260705-020): distinguish a JSON parse failure
      // (DimParseError / SyntaxError — the model emitted malformed JSON)
      // from a runtime/stream error, so the failed-dimension result records
      // the actual failure mode instead of an opaque "未知错误".
      const isParseFailure = error instanceof DimParseError || error instanceof SyntaxError
      const result = buildFailedDimensionResult(
        dimension,
        isParseFailure
          ? new Error(`${dimension.label}审查返回的 JSON 无法解析：${(error as Error).message}`)
          : error,
      )
      results[key] = result
      callbacks.onDimensionThinking?.(key, result.thinking)
      callbacks.onDimensionResult?.(key, result)
    }
  }
  return results
}

async function runDimensionStage(
  llmConfig: LlmConfig,
  dimension: SixReviewDimensionDefinition,
  userPrompt: string,
  callbacks: DimensionReviewCallbacks,
): Promise<string> {
  const messages: ChatMessage[] = [
    { role: "system", content: `你是专业网文审稿编辑，当前只负责“${dimension.label}”这一项审查。输出必须使用中文。` },
    { role: "user", content: userPrompt },
  ]
  let result = ""
  const streamCallbacks: StreamCallbacks = {
    onToken: (token: string) => {
      result += token
      callbacks.onThinking?.(dimension.key, formatDimensionThinking(dimension, result))
    },
    onDone: () => {},
    onError: (error: Error) => {
      console.error(`[Dimension Review] ${dimension.key} stream error:`, error)
    },
  }

  await streamChat(
    llmConfig,
    messages,
    streamCallbacks,
    AbortSignal.timeout(120000),
    { reasoning: { mode: useWikiStore.getState().novelConfig.reviewReasoningEffort ?? "high" } },
  )
  return result.trim()
}

function parseDimensionReviewResult(
  dimension: SixReviewDimensionDefinition,
  finalText: string,
  thinking: string,
): DimensionReviewResult {
  const jsonMatch = finalText.match(/\{[\s\S]*\}/)
  if (!jsonMatch) throw new Error(`${dimension.label}审查没有返回 JSON`)

  // F-003 (ISS-20260705-020): harden the unguarded JSON.parse. A SyntaxError
  // means the model emitted malformed JSON (truncation, code-fence leakage,
  // trailing prose) — wrap it in DimParseError so callers can distinguish a
  // parse failure from a runtime/stream failure. Non-SyntaxError throwables
  // are re-thrown unchanged.
  let parsed: Record<string, unknown>
  try {
    parsed = JSON.parse(jsonMatch[0]) as Record<string, unknown>
  } catch (error) {
    if (error instanceof SyntaxError) {
      throw new DimParseError(jsonMatch[0], error.message)
    }
    throw error
  }
  const issues = Array.isArray(parsed.issues) ? parsed.issues : []
  return {
    dimensionKey: dimension.key,
    score: normalizeScore(parsed.score),
    status: validateStatus(parsed.status, issues.length),
    summary: String(parsed.summary || ""),
    thinking: formatDimensionThinking(dimension, thinking),
    issues: issues.map((item) => normalizeIssue(dimension.key, item as Record<string, unknown>)),
  }
}

function normalizeIssue(dimensionKey: SixReviewDimensionKey, item: Record<string, unknown>): DimensionReviewIssue {
  const evidence = String(item.evidence || "")
  return {
    severity: validateSeverity(item.severity),
    type: String(item.type || dimensionKey),
    dimensionKey,
    message: String(item.message || ""),
    evidence,
    relatedMemory: String(item.relatedMemory || ""),
    suggestion: String(item.suggestion || ""),
    impact: String(item.impact || ""),
    rewriteTarget: String(item.rewriteTarget || evidence),
  }
}

function buildFailedDimensionResult(
  dimension: SixReviewDimensionDefinition,
  error: unknown,
): DimensionReviewResult {
  const message = error instanceof Error ? error.message : "未知错误"
  return {
    dimensionKey: dimension.key,
    score: 0,
    status: "error",
    summary: `${dimension.label}审查失败：${message}`,
    thinking: formatDimensionThinking(dimension, `审查失败：${message}`),
    issues: [{
      severity: "error",
      type: dimension.key,
      dimensionKey: dimension.key,
      message: `${dimension.label}审查失败：${message}`,
      evidence: "",
      relatedMemory: "",
      suggestion: "请检查模型设置后重新审查此维度。",
      impact: "该维度暂时没有可用审查结果。",
      rewriteTarget: "",
    }],
  }
}

function formatDimensionThinking(dimension: SixReviewDimensionDefinition, content: string): string {
  return `## ${dimension.label}\n${content.trim()}`
}

function normalizeScore(value: unknown): number {
  const score = typeof value === "number" ? value : Number(value)
  if (!Number.isFinite(score)) return 0
  return Math.max(0, Math.min(100, Math.round(score)))
}

function validateStatus(value: unknown, issueCount: number): DimensionReviewStatus {
  if (value === "error" || value === "high" || value === "medium" || value === "low" || value === "pass") {
    return value
  }
  return issueCount === 0 ? "pass" : "medium"
}

function validateSeverity(value: unknown): "error" | "warning" | "info" {
  if (value === "error" || value === "warning" || value === "info") return value
  return "warning"
}
